lsi: false
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["Rakefile", "upload.rb", "ftp-info.txt", "LICENSE.txt", "README.md", "CNAME"]
title: Pennyminder Application Development and Hosting for Credit Unions
url: http://pennyminder.com
